services:
  postgres:
    image: postgres:latest
    container_name: arvyax-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: arvyax
    ports:
      - "5432:5432"

volumes:
  postgres_data: